using MongoDB.Bson.Serialization.Attributes;

namespace DomnerTech.Backend.Domain.ValueObjects;

/// <summary>
/// Represents a Stock Keeping Unit (SKU) identifier.
/// </summary>
[BsonIgnoreExtraElements]
public sealed class SkuValueObject
{
    /// <summary>
    /// Gets or sets the SKU code.
    /// </summary>
    public required string Code { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether this SKU is auto-generated.
    /// </summary>
    public bool IsAutoGenerated { get; set; }

    public SkuValueObject()
    {
    }

    public SkuValueObject(string code, bool isAutoGenerated = false)
    {
        Code = code;
        IsAutoGenerated = isAutoGenerated;
    }

    public override bool Equals(object? obj)
    {
        return obj is SkuValueObject sku && Code == sku.Code;
    }

    public override int GetHashCode()
    {
        return Code.GetHashCode();
    }

    public override string ToString()
    {
        return Code;
    }
}
