using Bas24.CommandQuery;
using DomnerTech.Backend.Application.DTOs;
using DomnerTech.Backend.Application.Errors;
using DomnerTech.Backend.Application.Extensions;
using DomnerTech.Backend.Application.IRepo;
using DomnerTech.Backend.Application.Services;
using DomnerTech.Backend.Domain.Entities;
using DomnerTech.Backend.Domain.Enums;
using DomnerTech.Backend.Domain.ValueObjects;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using MongoDB.Bson;

namespace DomnerTech.Backend.Application.Features.Products.Handlers;

/// <summary>
/// Handler for creating a new product.
/// </summary>
public sealed class CreateProductCommandHandler(
    ILogger<CreateProductCommandHandler> logger,
    IProductRepo productRepo,
    ICategoryRepo categoryRepo,
    IProductService productService,
    ITenantService tenantService) : IRequestHandler<CreateProductCommand, BaseResponse<string>>
{
    public async Task<BaseResponse<string>> Handle(CreateProductCommand request, CancellationToken cancellationToken)
    {
        try
        {
            var dto = request.Dto;

            // Validate category exists
            var categoryId = dto.CategoryId.ToObjectId();
            var category = await categoryRepo.GetByIdAsync(categoryId, cancellationToken);
            if (category == null)
            {
                return new BaseResponse<string>
                {
                    Status = new ResponseStatus
                    {
                        StatusCode = StatusCodes.Status404NotFound,
                        ErrorCode = ErrorCodes.SystemError,
                        Desc = "Category not found"
                    }
                };
            }

            // Generate SKU if not provided
            var sku = string.IsNullOrWhiteSpace(dto.Sku)
                ? await productService.GenerateSkuAsync(categoryId, cancellationToken: cancellationToken)
                : dto.Sku;

            // Check if SKU already exists
            var existingProduct = await productRepo.GetBySkuAsync(sku, cancellationToken);
            if (existingProduct != null)
            {
                return new BaseResponse<string>
                {
                    Status = new ResponseStatus
                    {
                        StatusCode = StatusCodes.Status409Conflict,
                        ErrorCode = ErrorCodes.SystemError,
                        Desc = "Product with this SKU already exists"
                    }
                };
            }

            var now = DateTime.UtcNow;
            var productId = ObjectId.GenerateNewId();

            // Convert prices to value objects
            var prices = dto.Prices.Select(p => new ProductPriceValueObject
            {
                PriceType = p.PriceType,
                Currency = p.Currency,
                Amount = p.Amount,
                EffectiveFrom = p.EffectiveFrom,
                EffectiveTo = p.EffectiveTo
            }).ToList();

            // Convert barcodes to value objects
            var barcodes = dto.Barcodes?.Select(b => new BarcodeValueObject
            {
                Value = b.Value,
                Type = b.Type
            }).ToList();

            // Convert attributes to value objects
            var attributes = dto.Attributes?.Select(a => new ProductAttributeValueObject
            {
                Name = a.Name,
                Value = a.Value
            }).ToList();

            var entity = new ProductEntity
            {
                Id = productId,
                CompanyId = tenantService.CompanyId.ToObjectId(),
                Name = dto.Name,
                Description = dto.Description,
                Sku = new SkuValueObject
                {
                    Code = sku,
                    IsAutoGenerated = string.IsNullOrWhiteSpace(dto.Sku)
                },
                Barcodes = barcodes,
                CategoryId = categoryId,
                BrandId = dto.BrandId?.ToObjectId(),
                Prices = prices,
                CostPrice = dto.CostPrice,
                UnitOfMeasure = dto.UnitOfMeasure,
                Attributes = attributes,
                Images = dto.Images,
                HasVariants = false,
                IsBundle = false,
                Status = ProductStatus.Draft,
                TrackInventory = dto.TrackInventory,
                TrackBatchLot = dto.TrackBatchLot,
                TrackSerialNumber = dto.TrackSerialNumber,
                IsTaxable = dto.IsTaxable,
                TaxRate = dto.TaxRate,
                Weight = dto.Weight,
                Dimensions = dto.Dimensions,
                Tags = dto.Tags,
                WarehouseIds = dto.WarehouseIds?.Select(w => w.ToObjectId()).ToList(),
                CreatedAt = now,
                UpdatedAt = now,
                IsDeleted = false
            };

            await productRepo.CreateAsync(entity, cancellationToken);

            logger.LogInformation("Product created successfully: {ProductId} - {Sku}", productId, sku);

            return new BaseResponse<string>
            {
                Data = productId.ToString()
            };
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception e)
        {
            logger.LogError(e, "Error creating product: {Error}", e.Message);
        }

        return new BaseResponse<string>
        {
            Status = new ResponseStatus
            {
                StatusCode = StatusCodes.Status500InternalServerError,
                ErrorCode = ErrorCodes.SystemError
            }
        };
    }
}
